Zia enhancement-add commands
rootbid/xsoar-content pull request #2
Opened 2023-04-24 13:22 UTC by pallavi-garad

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Description
Add commands 'zscaler-get-ip-destination-groups-lite' and 'zscaler-delete-ip-destination-group'.
'zscaler-get-ip-destination-groups-lite' will retrieves name and ID dictionary of IPv4/IPv6 destination groups. 
'zscaler-delete-ip-destination-group' will deletes the IP destination group for the specified group ID.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [x] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

2023-04-25 03:32 UTC, rootbid commented on Packs/Zscaler/Integrations/Zscaler/Zscaler.py
> +            ipv6_responses = http_request('GET', ipv6_cmd_url).json()
Only these statements can result in `JSONDecodeError`, therefore these should only be inside the `try` block. Previous statements are not required to be under `try` block.

💡  Good practice is to keep the try block as small as possible: It's best to keep only the code that might raise an exception inside the try block. This makes it easier to locate the source of the error when an exception is raised.

2023-04-25 04:02 UTC, rootbid requested changes

2023-04-25 04:02 UTC, rootbid commented on Packs/Zscaler/Integrations/Zscaler/Zscaler.py
> +                        ipv6_cmd_url += f"&type={category_type[i]}"
This code block can be refactored as,
```py
if exclude_type:
    exclude_type_param = f"?excludeType={exclude_type}&"
else:
    exclude_type_param = "?"
type_params = [f"type={t}" for t in category_type]
type_params_str = "&".join(type_params)
ipv4_cmd_url += exclude_type_param +  type_params_str
ipv6_cmd_url += exclude_type_param + type_params_str
```

The main changes are:
1. Using a conditional expression to avoid repeating the same code for the `exclude_type` parameter.
2. Building the `type` parameters as a list of strings, and then joining them with the
`&` separator.
3. Concatenating the `exclude_type` parameter and the `type` parameters in a single step, instead of repeating the same logic for each URL.

2023-04-25 04:02 UTC, rootbid commented on Packs/Zscaler/Integrations/Zscaler/Zscaler.py
> +            ipv6_cmd_url = f"/ipDestinationGroups/ipv6DestinationGroups/lite"
Not required to be an f-string

2023-04-25 04:02 UTC, rootbid commented on Packs/Zscaler/Integrations/Zscaler/Zscaler.py
> +        }
You can use a function to reduce the repetition of code. Here's an example of how you can refactor the code block:
```py
def get_contents_lite(responses, type):
    contents = list()
    for response in responses:
        content = {
            'ID': response.get('id', ''),
            'Name': response.get('name', ''),
            'extensions': response.get('extensions', {})
        }
        contents.append(content)
    return {type: contents}
ipv4_contents = get_contents_lite(ipv4_responses, "IPv4")
ipv6_contents = get_contents_lite(ipv6_responses, "IPv6")
s_content = {
    **ipv4_contents,
    **ipv6_contents
}
```

2023-04-25 04:02 UTC, rootbid commented on Packs/Zscaler/Integrations/Zscaler/Zscaler.py
> +            contents.append(content)
Previous comments may also guide the refactor for this implementation. 😸

2023-04-25 04:02 UTC, rootbid commented on Packs/Zscaler/Integrations/Zscaler/Zscaler.yml
> +      description: Fetch the ipv6 Destination Groups.
`ipv6` -> `IPv6`

2023-04-25 09:40 UTC, pallavi-garad commented on Packs/Zscaler/Integrations/Zscaler/Zscaler.py
> +                        ipv6_cmd_url += f"&type={category_type[i]}"
done

2023-04-25 09:41 UTC, pallavi-garad commented on Packs/Zscaler/Integrations/Zscaler/Zscaler.py
> +        }
done

2023-04-25 09:41 UTC, pallavi-garad commented on Packs/Zscaler/Integrations/Zscaler/Zscaler.yml
> +      description: Fetch the ipv6 Destination Groups.
done

2023-04-25 09:41 UTC, pallavi-garad commented on Packs/Zscaler/Integrations/Zscaler/Zscaler.py
> +            contents.append(content)
done

2023-04-25 09:42 UTC, pallavi-garad commented on Packs/Zscaler/Integrations/Zscaler/Zscaler.py
> +            ipv6_cmd_url = f"/ipDestinationGroups/ipv6DestinationGroups/lite"
done

2023-05-08 04:08 UTC, rootbid approved these changes

2023-05-08 04:09 UTC, rootbid commented
`Limit` based pagination is missing in `list-ip-destination-groups-lite` command?

2023-05-10 10:23 UTC, rootbid commented
Manually resolved conflicts and merged changes.

2023-05-10 10:23 UTC, closed without merging